name: epigrass
version: "3.0.0"
summary: Epidemiological Geo-Referenced Analysis and Simulation System
description: EpiGrass is a simulator of epidemics over networks.  Its is a scientific tool created for
              simulations and scenario analysis in Network epidemiology.
confinement: strict

apps:
  epigrass:
    command: epigrass
  epirunner:
    command: epirunner

parts:
  epigrass:
    plugin: python2
    source: git://github.com/fccoelho/epigrass.git

  numpy:
    plugin: python2
    source-type: tar
    source : https://pypi.python.org/packages/1d/94/3ad9a865f1b0853f952eaa9878c59371ac907b768fe789547f573a6c9b39/numpy-1.10.4.tar.gz#md5=aed294de0aa1ac7bd3f9745f4f1968ad
