{% set name = "epigrass" %}
{% set version = "3.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7d98ca1441a4ef3f2eaf6d2c8a7919bde9c6ce488259e02e9f1f9218b07e5111

build:
  number: 0
  entry_points:
    - epirunner = Epigrass.manager:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - altair
    - cython
    - datashader
    - dbfread
    - epimodels
    - fiona
    - geopandas
    - geoviews
    - holoviews
    - matplotlib
    - networkx
    - numpy
    - pandas
    - panel
    - pip
    - pweave
    - pymysql
    - python
    - redis
    - scikit-image
    - shapely
    - sqlalchemy
    - sqlobject
    - tqdm
    - redis-py
  run:
    - altair
    - cython
    - datashader
    - dbfread
    - epimodels
    - fiona
    - geopandas
    - geoviews
    - holoviews
    - matplotlib
    - networkx
    - numpy
    - pandas
    - panel
    - pweave
    - pymysql
    - python
    - redis
    - scikit-image
    - shapely
    - sqlalchemy
    - sqlobject
    - tqdm
    - redis-py

test:
  imports:
    - Epigrass
  commands:
    - epirunner --help

about:
  home: "http://epigrass.sourceforge.net"
  license: GPL
  license_family: GPL
  license_file: 
  summary: "Epidemiological Geo-Referenced Analysis and Simulation System"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - fccoelho
